---
#
# This file creates AWS security groups

 - name: Create Security Group
   ec2_group:
      name: ec2_secure
      description: Create Security Group for HTTP/HTTPS/SSH
      region: "{{ ec2_region }}"
      rules:
       - proto: tcp
         type: http
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         type: https
         from_port: 443
         to_port: 443
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         type: ssh
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
      rules_egress: 
       - proto: all
         cidr_ip: 0.0.0.0/0

 - name: Create EC2 Instance
   ec2:
      group: ec2_secure
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      wait: true
      count: 1
      volumes:
       - device_name: /dev/sda1
         volume_size: 4
         delete_on_termination: true
   register: ec2

 - debug: var={{ item }}
   with_items: "{{ ec2.instances }}"

 - name: Wait for instances to boot by checking ssh port
   wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
   with_items: "{{ ec2.instances }}"


